0xd34d10cc/shar

CMakeLists.txt
src/main.cpp
src/texture.cpp
src/texture.hpp
src/window.hpp

CMake win32 fixes

---

.travis.yml

proof of work: https://travis-ci.org/pl0q1n/shar/builds/393236341

Travis integration init commit (with clang support only)

---

CMakeLists.txt
src/codecs/h264/decoder.cpp
src/codecs/h264/encoder.cpp
src/disable_warnings_pop.hpp
src/main.cpp
src/primitives/image.cpp
src/processors/capture_frame_provider.cpp
src/processors/frame_display.hpp
src/processors/h264decoder.cpp
src/processors/h264encoder.cpp
src/processors/packet_receiver.cpp
src/processors/packet_receiver.hpp
src/processors/packet_sender.cpp
src/processors/packet_sender.hpp
src/processors/processor.cpp
src/processors/processor.hpp
src/window.cpp

- Added -Werror to compiler flags for clang builds
- Implemented PacketSender && PacketReceiver
- Fixed bunch of warnings

Network layer

---

CMakeLists.txt
src/codecs/h264/encoder.cpp
src/main.cpp
src/primitives/image.cpp
src/primitives/image.hpp
src/primitives/timer.hpp
src/processors/capture_frame_provider.cpp
src/processors/frame_file_reader.cpp
src/processors/frame_file_reader.hpp
src/processors/frame_file_writer.cpp
src/processors/frame_file_writer.hpp
utils/CMakeLists.txt
utils/latency.cpp
utils/play.cpp
utils/record.cpp

Closes #13 
- Implemented encoder latency test
- Added utilities to record and play raw bgra streams
NOTE: this code should be refactored just after #11

Encoder latency test

---

conanfile.txt
src/client/CMakeLists.txt
src/client/main.cpp
src/codecs/convert.cpp
src/codecs/convert.hpp
src/codecs/ffmpeg/decoder.cpp
src/codecs/ffmpeg/decoder.hpp
src/codecs/ffmpeg/encoder.cpp
src/codecs/ffmpeg/encoder.hpp
src/codecs/openh264/decoder.cpp
src/codecs/openh264/decoder.hpp
src/codecs/openh264/encoder.cpp
src/codecs/openh264/encoder.hpp
src/packet.cpp
src/packet.hpp
src/processors/h264decoder.cpp
src/processors/h264decoder.hpp
src/processors/h264encoder.cpp
src/processors/h264encoder.hpp
src/processors/screen_capture.cpp
src/processors/screen_capture.hpp
src/server/CMakeLists.txt
src/server/main.cpp
src/utils/CMakeLists.txt
src/utils/ffmpeg_test.cpp
src/utils/full_pipeline_test.cpp
src/utils/latency.cpp
src/utils/record.cpp
src/window.cpp

Video stream compression with ffmpeg

---

CMakeLists.txt
src/codecs/ffmpeg/encoder.cpp
src/packet.cpp
src/packet.hpp
src/processors/packet_sender.cpp
src/processors/packet_sender.hpp
src/server/main.cpp

Correct cient initialization

---

conf/config.json
src/codecs/ffmpeg/encoder.cpp
src/codecs/ffmpeg/encoder.hpp
src/config.hpp
src/processors/h264encoder.cpp
src/processors/h264encoder.hpp
src/processors/packet_sender.hpp
src/server/CMakeLists.txt
src/server/main.cpp
src/utils/full_pipeline_test.cpp
src/utils/latency.cpp

Encoder configuration

---

src/codecs/ffmpeg/decoder.cpp
src/codecs/ffmpeg/encoder.cpp
src/logger.hpp
src/processors/h264encoder.hpp
src/processors/packet_sender.cpp
src/window.cpp

- Fixed memory leaks (ffmpeg packets, frames, encoder options)
- Fixed crash that happens in case if any asio task was active on shutdown
- Fixed crash in window initialization

Fix memory leaks (ffmpeg-related code)

---

conanfile.py
src/client/CMakeLists.txt
src/client/main.cpp
src/client/options.cpp
src/client/options.hpp
src/forwarding.cpp
src/forwarding.hpp
src/server/CMakeLists.txt
src/server/main.cpp

Closes #30 
- Refactor options in client
- Remove openh264 from dependencies
- Implement port forwarding using miniupnpc

Port forwarding

---

conf/config.json
src/codecs/ffmpeg/encoder.cpp

Options to increase the quality of streaming image.

some options for encoder config

---

.appveyor.yml
.travis.yml
conanfile.py

AMF encoder introduction

---

src/processors/packet_sender.cpp
src/processors/packet_sender.hpp

PacketSender reconnect

---

CMakeLists.txt

Fix for CMake on MacOS

---

.travis.yml
.vs/launch.vs.json
CMakeLists.txt
CMakeSettings.json
conf/config.json
conf/stream.sdp
scripts/setup.bat
src/app/main.cpp
src/encoder/encoder.cpp
src/encoder/encoder.hpp
src/encoder/ffmpeg/avcontext.cpp
src/encoder/ffmpeg/avcontext.hpp
src/encoder/ffmpeg/codec.cpp
src/encoder/ffmpeg/codec.hpp
src/network/CMakeLists.txt
src/network/fragment.hpp
src/network/module.hpp
src/network/network.cpp
src/network/network.hpp
src/network/packetizer.cpp
src/network/packetizer.hpp
src/network/rtnet/CMakeLists.txt
src/network/rtnet/byteorder.cpp
src/network/rtnet/tests/CMakeLists.txt
src/network/rtp.cpp
src/network/rtp.hpp
src/network/tcp.cpp
src/network/tcp.hpp
src/network/url.cpp
src/network/url.hpp

Implement Url and NetworkModule abstraction. Bring back tcp streaming.

---

conanfile.py
src/CMakeLists.txt
src/app/app.cpp
src/common/config.hpp
src/encoder/ffmpeg/codec.cpp
src/network/CMakeLists.txt
src/network/rtnet/rtp/session.hpp
src/network/rtp.cpp
src/network/rtp.hpp
src/network/tcp.cpp
src/network/tcp.hpp
src/network/url.hpp

Remove boost dependency

---

CMakeSettings.json
scripts/setup.bat

Add x64-Profile target

---

src/app/main.cpp
src/app/view.cpp
src/common/options.cpp
src/common/options.hpp
src/ui/display.cpp
src/ui/display.hpp
src/ui/startup_screen.cpp
src/ui/startup_screen.hpp

Implement startup screen

---

src/app/broadcast.cpp
src/app/broadcast.hpp
src/capture/capture.cpp
src/capture/capture.hpp
src/codec/ffmpeg/frame.cpp
src/ui/renderer.cpp
src/ui/renderer.hpp
src/ui/startup_screen.cpp

Closes #149 in the most simple and stupid way possible

Duplicate Frame in ScreenCapture. Run Display in Broadcast.

---

src/app/app.cpp
src/app/runner.cpp
src/ui/CMakeLists.txt
src/ui/message_box.cpp
src/ui/message_box.hpp

Show message box in case of unhandled exception

---

src/app/app.cpp
src/app/app.hpp
src/ui/CMakeLists.txt
src/ui/rect.hpp
src/ui/window.cpp
src/ui/window.hpp

Implement custom title bar

---

src/app/app.cpp
src/app/app.hpp
src/app/view.cpp
src/ui/CMakeLists.txt
src/ui/button.cpp
src/ui/button.hpp

- Refactor GUI processing
- Handle stream start errors 
- Implement Button wrapper
Closes #161

Refactor GUI processing. 

---

CMakeLists.txt
modules/platform.cmake
modules/warnings.cmake
src/app/app.cpp
src/capture/capture.cpp
src/common/disable_warnings_push.hpp
src/network/rtnet/rtcp/source_items.cpp
src/network/rtnet/rtsp/parser.cpp
src/ui/window.cpp

Enable /W4 for msvc builds. Fix all warnings.

---

src/app/app.cpp
src/codec/ffmpeg/codec.cpp
src/codec/ffmpeg/unit.cpp
src/codec/ffmpeg/unit.hpp
src/common/options.hpp
src/common/time.hpp
src/net/CMakeLists.txt
src/net/receiver_factory.cpp
src/net/rtp/depacketizer.cpp
src/net/rtp/depacketizer.hpp
src/net/rtp/packet.cpp
src/net/rtp/receiver.cpp
src/net/rtp/receiver.hpp
src/net/rtp/sender.cpp
src/net/rtp/sender.hpp
src/net/tcp/receiver.hpp

Implement very basic RTP receiver
Current problems:
- client side is not able to display it correctly
- hangs if stop button is clicked

RTP Receiver

---

src/net/rtp/depacketizer.cpp
src/net/rtp/depacketizer.hpp
src/net/rtp/receiver.cpp
src/net/rtp/receiver.hpp

Buffer rtp packets by timestamp

---

src/net/CMakeLists.txt
src/net/stun/attributes.cpp
src/net/stun/attributes.hpp
src/net/stun/client.cpp
src/net/stun/message.cpp
src/net/stun/message.hpp

Implement stun::Message, stun::Attributes. Add test stun client.

---

src/net/receiver_factory.cpp
src/net/sender_factory.cpp
src/net/url.cpp
src/net/url.hpp

Support hostnames in URL

---

src/net/CMakeLists.txt
src/net/rtp/tests/depacketizer.cpp

Implement UTs for rtp::Depacketizer

---

src/app/app.cpp
src/app/app.hpp
src/app/broadcast.cpp
src/app/broadcast.hpp
src/app/view.cpp
src/app/view.hpp
src/common/CMakeLists.txt
src/common/atomic_string.cpp
src/common/atomic_string.hpp

Propagate exceptions from background threads

---

src/app/app.cpp
src/app/app.hpp
src/ui/window.cpp
src/ui/window.hpp

Update on timer while window is being dragged

---

src/net/CMakeLists.txt
src/net/stun/attributes.hpp
src/net/stun/error.hpp
src/net/stun/request.cpp
src/net/stun/request.hpp
src/net/stun/stunc.cpp

Also added support for MAPPED_ADDRESS response type

Extract stun request processing logic to separate class

---

src/net/CMakeLists.txt
src/net/stun/tests/message.cpp

Implement UTs for stun::Message

---

src/app/app.cpp
src/app/app.hpp
src/app/broadcast.cpp
src/app/broadcast.hpp
src/app/view.cpp
src/app/view.hpp
src/capture/capture.cpp
src/capture/capture.hpp

It makes UI much more responsive. Especially in debug mode.
Closes #200

Move yuv -> bgra conversion to background thread

---

src/app/app.cpp
src/app/app.hpp

Re-render only if either some input event was processed or new frame was received

---

src/ui/window.cpp

Enable window shadow (win32)

---

src/app/app.cpp
src/ui/renderer.cpp
src/ui/renderer.hpp

Render frame 30 pixels lower

---

src/app/app.cpp
src/ui/renderer.cpp
src/ui/renderer.hpp
src/ui/window.cpp
src/ui/window.hpp

Allow to resize window

---

src/app/app.cpp
src/common/cancellation.cpp

Preserve aspect ratio if window is resized

---

src/app/app.cpp
src/app/app.hpp
src/common/cancellation.cpp
src/common/cancellation.hpp

Update metrics when window is dragged

---

src/app/app.cpp
src/ui/state.cpp
src/ui/text_edit.cpp
src/ui/text_edit.hpp

Editable address

---

src/net/rtsp/parser.cpp
src/net/rtsp/response.cpp
src/net/rtsp/server.cpp

Implement (sort of) rtsp 2.0 parser

---

.travis.yml

closes #83 
current status - https://travis-ci.org/github/0xd34d10cc/shar/jobs/695625835

Provide macos build for Travis

---

src/app/app.cpp
src/app/view.cpp
src/capture/capture.cpp
src/codec/ffmpeg/codec.cpp
src/codec/ffmpeg/codec.hpp
src/common/size.hpp
src/ui/renderer.cpp
src/ui/texture.cpp
src/ui/texture.hpp

Remove magic constants related to monitor size & aspect ratio

---

.travis.yml
conanfile.py
modules/warnings.cmake

Fix Linux CI build 

---

.github/workflows/ci.yml
Cargo.toml

Generate ffmpeg bindings only for libavcodec

---

.github/workflows/ci.yml
src/main.rs

Setup cache for cargo

---

Cargo.toml
src/codec/ffmpeg/codec.rs
src/codec/ffmpeg/encoder.rs
src/main.rs
src/view.rs

- Set profile=medium, tune=zerolatency for ffmpeg. 
- Fix bitrate (should be in bits instead of kbits)
Closes #139

Set ffmpeg options

---

src/capture.rs
src/main.rs
src/net/tcp/receiver.rs

Allow to pick monitor to capture

---

src/main.rs
src/ui/mod.rs
src/ui/style/dark.rs
src/ui/style/light.rs
src/ui/style/mod.rs

Add dark theme

---

.github/workflows/ci.yml
src/codec/ffmpeg/unit.rs
src/net/rtp/depacketizer.rs
src/net/rtp/fragment.rs
src/net/rtp/mod.rs
src/net/rtp/receiver.rs
src/view.rs

Implement RTP receiver

---

Cargo.toml
src/capture.rs
src/codec/ffmpeg/error.rs
src/main.rs
src/net/rtp/packetizer.rs
src/net/rtp/receiver.rs
src/net/rtp/sender.rs
src/net/tcp/receiver.rs
src/net/tcp/sender.rs
src/stream.rs
src/ui/app.rs
src/ui/style/dark.rs
src/ui/views/main.rs

Update all dependencies

---

Cargo.toml
src/ui/app.rs
src/ui/config.rs
src/ui/mod.rs
src/ui/views/app_config.rs
src/ui/views/main.rs
src/ui/views/mod.rs

Implement a separate view for application-wide configuration
